# Generated by Django 4.2.3 on 2023-08-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0003_alter_advertisment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
